trigger: none

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalWin

parameters:
  - name: environment
    displayName: "Target Environment"
    type: string
    default: dev
    values:
      - dev
      - test

  - name: createAI
    displayName: "Create AppInsights"
    type: boolean
    default: false

  - name: createSA
    displayName: "Create Sorage Account"
    type: boolean
    default: false

stages:
  - stage: createAIStage
    condition: eq('${{ parameters.createAI }}', true)
    displayName: 'Create AI'    
    jobs:
    - job:
    - template: templates/linting.yaml
    - template: templates/dryrun.yaml
  - stage: createAIStage
    condition: eq('${{ parameters.createSA }}', true)
    displayName: 'Create Storage Account'    
    jobs:
    - job:
    - template: templates/linting.yaml
    - template: templates/dryrun.yaml
