trigger: none

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalWin

parameters:
  - name: environment
    displayName: "Target Environment"
    type: string
    default: dev
    values:
      - dev
      - test

  - name: createAI
    displayName: "Create AppInsights"
    type: string
    default: No
    values:
      - Yes
      - No

  - name: createSA
    displayName: "Create Sorage Account"
    type: string
    default: No
    values:
      - Yes
      - No

stages:
  - stage: createAIStage
    condition: eq('${{ parameters.createAI }}', 'Yes')
    displayName: 'Create AI'    
    jobs:
    - template: linting.yaml
    - template: dryrun.yaml
  - stage: createAIStage
    condition: eq('${{ parameters.createSA }}', 'Yes')
    displayName: 'Create Storage Account'    
    jobs:
    - template: linting.yaml
    - template: dryrun.yaml
